server {
    server_name www.api.careride.com;
    return 301 https://api.careride.com$request_uri;
}

server {
    listen 80;
    server_name api.careride.com;
    rewrite ^ https://$host$request_uri? permanent;
}

#server {
#    listen 80;
#    listen [::]:80;
#    server_name api.careride.com;
#    charset utf-8;
#
#    location / {
#        access_log off;
#        proxy_pass http://node_backend:3000;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header Host $http_host;
#        proxy_set_header X-NginX-Proxy true;
#    }
#
#    client_max_body_size 100m;
#}

server {
    server_name www.careride.com;
    return 301 https://careride.com$request_uri;
}

server {
    listen 80;
    server_name careride.com;
    rewrite ^ https://$host$request_uri? permanent;
}

#server {
#    listen 80;
#    listen [::]:80;
#    server_name careride.com;
#    charset utf-8;
#
#    location / {
#        root   /usr/share/nginx/html;
#        try_files $uri $uri/ /index.html;
#    }
#
#    client_max_body_size 100m;
#}
