server {
    server_name www.pay.ibusxcoin.com;
    return 301 $scheme://pay.ibusxcoin.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name pay.ibusxcoin.com;
    charset utf-8;

    ssl on;
    ssl_certificate /etc/nginx/conf.d/pay.ibusxcoin.com/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/pay.ibusxcoin.com/server.key;

    location /ws {
        # switch off logging
        access_log off;

        # redirect all HTTP traffic to localhost
        proxy_pass http://php_payment:8090;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Path rewriting
        rewrite /ws/(.*) /$1 break;
        proxy_redirect off;

        # timeout extension, possibly keep this short if using a ping strategy
        proxy_read_timeout 99999s;
    }

    location / {
        access_log off;
        proxy_pass http://php_payment:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name pay.ibusxcoin.com;
    rewrite ^ https://$host$request_uri? permanent;
}

server {
    server_name www.admin.ibusxcoin.com;
    return 301 $scheme://admin.ibusxcoin.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name admin.ibusxcoin.com;
    charset utf-8;

    ssl on;
    ssl_certificate /etc/nginx/conf.d/admin.ibusxcoin.com/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/admin.ibusxcoin.com/server.key;

    location / {
        access_log off;
        proxy_pass http://php_admin:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name admin.ibusxcoin.com;
    rewrite ^ https://$host$request_uri? permanent;
}