
server {
    listen 80;
    listen [::]:80;
    server_name api.careride.com;
    charset utf-8;

    location / {
        access_log off;
        proxy_pass http://node_backend:3000;
        # proxy_pass http://carer-LoadB-L0I4P1PL53T4-0bd2fb0612ea7ab0.elb.us-west-1.amazonaws.com:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name careride.com;
    charset utf-8;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
