FROM node:14-bullseye

RUN apt-get update && apt-get install -y \
        nano \
        nginx \
        curl 

WORKDIR /var/www/html

COPY package*.json ./
COPY . /var/www/html

RUN npm install
RUN npm install pm2 -g

RUN  rm /var/www/html/server/config.js
COPY ./deploy/config.js /var/www/html/server/config.js

RUN  echo "client_max_body_size 100m;" > /etc/nginx/conf.d/body.conf
RUN  rm /etc/nginx/sites-available/default
COPY ./deploy/deploy.conf  /etc/nginx/sites-available/default

CMD ["npm", "run", "start"]



EXPOSE 80





